server:
  port: 9001
spring:
  application:
    name: mall-admin
  cloud:
    nacos:
      discovery:
        ip: 127.0.0.1
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_ums
    username: root
    password: passwordZWL159!
